### ISSUE TITLE
PowerShell Gallery issues

### ISSUE THREAD

**Issue by johnwc** [iRon7/Join-Object#2]
I can't get this to work when installing it from PSGallery. I install it with `Install-Script -Name Join`, and when I try to use Join it just comes back immediately with nothing. If I try to call Join.ps1, same thing. If I call Join-Object, it gives me an error.

Looking at the ConvertFrom-Docker PSGallery script, the ps1 is written as a cmdlet. Do you need to do that? Also, I am unable to use or see any of the Alias's being set. How do you use this when installing from PSGallery?

```PowerShell
PS C:\> Join
PS C:\> Join.ps1
PS C:\> Join-Object
Join-Object : The term 'Join-Object' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ Join-Object
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Join-Object:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I edited the ps1 file and added `Global:` in front of `Join-Object`, like the following and I was able to at least run Join.ps1 and then use Join-Object.

```PowerShell
Function Global:Join-Object { … }
```

Also, after I was able to make the function global. When I tried to run the test you replied to in the SO site; https://stackoverflow.com/a/45563467/3117194, it does not merge them correctly.

```PowerShell
PS C:\> $Json1 = '{a:{b:"asda"},c: "asdasd"}'  | ConvertFrom-Json
PS C:\> $Json2 = '{a:{b:"d"}}'  | ConvertFrom-Json
PS C:\> $Json1 | Join-Object $Json2 -Merge {$Right.$_}

c a
- -
  @{b=d}
```

C seems to have been set to nothing, when it should have been left alone.

**Comment by iRon7** [comment]
As it concerns a script (and not a module), you can simply invoke it using the PowerShell [dot sourcing](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_scripts?view=powershell-6#script-scope-and-dot-sourcing) feature. E.g.: `. .\Join.ps1`.

**Comment by johnwc** [comment]
Still gives an error.

```PowerShell
PS C:\> . .\Join.ps1
. : The term '.\Join.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:3
+ . .\Join.ps1
+   ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Join.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by iRon7** [comment]
`.\Join.ps1` is presuming that you installed the script in the current folder.
If you like to invoke the script from another location, you will need to provide the complete path, e.g.:
`. $env:ProgramFiles\WindowsPowerShell\Scripts\Join.ps1`
For details on locations used by the [`Install-Script` cmdlet](https://docs.microsoft.com/powershell/module/powershellget/install-script?view=powershell-6), see: https://docs.microsoft.com/en-us/powershell/gallery/getting-started#install
See, also StackOverflow for simular questions, like: [Loading custom functions in PowerShell](https://stackoverflow.com/questions/18764312/loading-custom-functions-in-powershell)
If you want to load the `Join.ps1` (or any other script) script by default (or make it easier available) you might consider to include to location or invocation in your [`$Profile`](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6), see e.g.: [Load all functions into PowerShell from a certain directory](https://stackoverflow.com/questions/763799/load-all-functions-into-powershell-from-a-certain-directory/763953#763953)
As this question is not directly related to this specific script but generally to the PowerShell Gallery and invoking scripts, I advice you to check for an answer or more help on a forum like [**StackOverflow**](https://stackoverflow.com/). In case, you can't find your answer there or need more help, I recommend you to open a new question on that same site so that others can also benefit from the question and answer.
