### ISSUE TITLE
out-join $null change to ''

### ISSUE THREAD

**Issue by ericxin1982** [iRon7/Join-Object#32]
Hi @iRon7 

The SQL API has isnull(null,'') then I can have value '', join-object outer-join has $null result, is there any way I can make result $null to ''?

Thanks
Eric Xin

**Comment by iRon7** [comment]
I am not sure whether I understand the question as this appears to me as a general PowerShell (rather than a specific `Join-Object`) question. In PowerShell you can easily force any object, including `$Null`, to a string by surrounding it by double quotes, like: `"$Object"`. Meaning you can use for example a PowerShell cmdlet as [`Select-Object`](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/select-object) with a [calculated property](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_calculated_properties) like: `... |Join-Object ... |Select-Object -Property @{Label = 'Id', Expression = { "$($_.Id)" } }` (or something like: `@{Label = 'Id', Expression = { if ($Null -eq $_) { "" } else { $_} } }`. `Join-Object,` can do something similar but uses a simplified calculated property, e.g.: `Join-Object -Property @{ Id = "$($Left.Id)" } `.

**Comment by ericxin1982** [comment]
Thanks so much!
